# Generated by Django 2.0.3 on 2019-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='datetime_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
